options:
  logging: 'CLOUD_LOGGING_ONLY' 

substitutions:
  _PROJECT_ID: 'modern-heading-440004-q8'  
  _IMAGE_NAME: 'python_pro7'  
  _DEPLOYMENT_NAME: 'python-pro1' 

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - '$_DEPLOYMENT_NAME'
      - '--image'
      - 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
      - '--region'
      - 'us-central1'
      - '--port=8080'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
