name: Deploy to Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'modern-heading-440004-q8' 
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/$GCP_PROJECT_ID/cloud-run-source-deploy/my-app
          docker build -t $IMAGE_NAME  .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/$GCP_PROJECT_ID/cloud-run-source-deploy/my-app
          gcloud run deploy my-app \
            --image $IMAGE_NAME \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
